package com.dynamoairlineservice.app.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@DynamoDbBean
public class Airline {

	
	private String airlineId;
	private String airlineName;
	private String airlineAddress;
	private String airlineContact;
	
	private boolean airlineStatus;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDbPartitionKey
	@DynamoDBHashKey(attributeName="airlineId")
	public String getAirlineId() {
		return airlineId;
	}

	public void setAirlineId(String airlineId) {
		this.airlineId = airlineId;
	}
	
	@DynamoDbSortKey
	public String getAirlineName() {
		return airlineName;
	}

	public void setAirlineName(String airlineName) {
		this.airlineName = airlineName;
	}

	@DynamoDbAttribute(value = "airlineAddress")
	public String getAirlineAddress() {
		return airlineAddress;
	}

	public void setAirlineAddress(String airlineAddress) {
		this.airlineAddress = airlineAddress;
	}

	@DynamoDbAttribute(value = "airlineContact")
	public String getAirlineContact() {
		return airlineContact;
	}

	public void setAirlineContact(String airlineContact) {
		this.airlineContact = airlineContact;
	}

	@DynamoDbAttribute(value = "airlineStatus")
	public boolean getAirlineStatus() {
		return airlineStatus;
	}

	public void setAirlineStatus(boolean airlineStatus) {
		this.airlineStatus = airlineStatus;
	}

	@Override
	public String toString() {
		return "Airline [airlineId=" + airlineId + ", airlineName=" + airlineName + ", airlineAddress=" + airlineAddress
				+ ", airlineContact=" + airlineContact + ", airlineStatus=" + airlineStatus + "]";
	}

	public Airline(String airlineId, String airlineName, String airlineAddress, String airlineContact,
			boolean airlineStatus) {
		super();
		this.airlineId = airlineId;
		this.airlineName = airlineName;
		this.airlineAddress = airlineAddress;
		this.airlineContact = airlineContact;
		this.airlineStatus = airlineStatus;
	}
	
	public Airline() {}
}
